# Generated by Django 2.1.8 on 2020-04-22 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('band', models.CharField(max_length=128, verbose_name='品牌')),
                ('platform', models.CharField(max_length=128, null=True, verbose_name='平台')),
                ('code', models.CharField(max_length=128, null=True, verbose_name='代号')),
                ('filepath', models.CharField(max_length=2000, null=True, verbose_name='文件路径')),
                ('modelpath', models.CharField(max_length=2000, null=True, verbose_name='模型路径')),
            ],
            options={
                'verbose_name': '模型信息表',
                'verbose_name_plural': '模型信息表',
            },
        ),
        migrations.CreateModel(
            name='ModelTag',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('tagname', models.CharField(max_length=512, verbose_name='标签名称')),
                ('modelcon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelRes.ModelInfo', verbose_name='模型信息表外键')),
            ],
            options={
                'verbose_name': '模型标签表',
                'verbose_name_plural': '模型标签表',
            },
        ),
        migrations.CreateModel(
            name='ModelType',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('type', models.CharField(max_length=128, verbose_name='类别')),
                ('remark', models.CharField(max_length=512, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '类别表',
                'verbose_name_plural': '类别表',
            },
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelRes.ModelType', verbose_name='类别'),
        ),
    ]
